### ISSUE TITLE
Make sure Landslides.verified.csv is accessible on GitHub

### ISSUE THREAD

**Issue by LManak** [mthomp89/landslide-detect#28]
@mthomp89 We still need to find a way to have this be more reproducible. Should we have the csv of the landslide dataset on Git Hub for future downloads so we don't have to do it manually on our own computer/ so other people have access to the csv when they create their working directory? I don't see it on GitHub yet. I think we just manually added it to our landslide-detect folder.

**Comment by mthomp89** [comment]
Best practices involve not uploading data to Github but for this purpose I did. Added a folder to main branch called data and uploaded two spreadsheets.
