### ISSUE TITLE
Discover, build automated way to capture relative orbit number (start)

### ISSUE THREAD

**Issue by mthomp89** [mthomp89/landslide-detect#5]
@LManak office hours (Elsa) orbit number

**Comment by mthomp89** [comment]
Problem is not being able to correctly query the database with specific spatial and temporal requirements. Some options would be Google EE itself like we are doing now ([using Part I of the series of notebooks](https://developers.google.com/earth-engine/tutorials/community/detecting-changes-in-sentinel-1-imagery-pt-1) or the [Sentinelsat library] (https://sentinelsat.readthedocs.io/en/stable/index.html) or direct search and data download from the [Open Access Hub](https://scihub.copernicus.eu/) just to get us started.

**Comment by LManak** [comment]
Was able to find the relative orbit # in im_coll by commenting out :
.filter(ee.Filter.eq('relativeOrbitNumber_start', 27))

and with this function: 
timestamplist = (im_coll.aggregate_array('relativeOrbitNumber_start')
                 .map(lambda d: ee.String('T').cat(ee.String(d)))
                 .getInfo())

Still needing to find a way to capture relative orbit # in an automated way.

**Comment by mthomp89** [comment]
Included the timestamplist variable in the new image_search function. closing this for now.
