### ISSUE TITLE
Identify different parameters in im_coll that we may or may not need to filter out

### ISSUE THREAD

**Issue by LManak** [mthomp89/landslide-detect#6]
We are currently filtering the following, however it could be worth looking into and playing around with different parameters:
           .filterBounds(aoi)
           .filterDate(ee.Date('2016-09-01'), ee.Date('2017-09-01'))
           .filter(ee.Filter.eq('orbitProperties_pass', 'DESCENDING'))
           .filter(ee.Filter.eq('relativeOrbitNumber_start', 27))
           .filter(ee.Filter.listContains('transmitterReceiverPolarisation',
                                          'VV'))
           .filter(ee.Filter.listContains('transmitterReceiverPolarisation',
                                          'VH'))

**Comment by mthomp89** [comment]
New filtering is set up in the image_search function. Closing this for now.
