### ISSUE TITLE
Reviewing the colors of the maps at the end

### ISSUE THREAD

**Issue by LManak** [mthomp89/landslide-detect#8]
Instead of blue and red, look into what makes those colors, and if the red/blue is confusing for what data we are actually displaying!

**Comment by mthomp89** [comment]
I like the thought here! Often in change detection in SAR, the commonality is Red-Fled, Blue-New. Meaning red is displacement away from previous location while blue is new object/materials where it didn't exist before. This helps to understand the changes in the scene as SAR is very difficult to interpret. That said, we should definitely consider changes to the color map.

**Comment by LManak** [comment]
@mthomp89 I just made all of the "definiteness" of change red. I.E. all of the change will be just the one red color for the cmaps.
